name: indulge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: '>=6.0.4'
  flutter_rating: ^2.0.2
  json_annotation: ^4.9.0
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.0.0+1
  path: ^1.9.0
  flutter_card_swiper: ^7.0.2
  swipe_cards: ^2.0.0+1
  pure_dart_ui: ^0.1.10
  enough_platform_widgets: ^1.0.0
  button_multiselect: ^0.0.3
  email_validator: '^2.1.17'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/reviews.json
    - assets/lists.json
    - 'assets/young-woman-eating-ramen.png'
    - 'assets/profile-avatar-placeholder.png'
    - assets/dummy_restaurants.json


